SELECT ID, NAZWA FROM B_KATEGORIE ORDER BY NAZWA;


SELECT ID
FROM B_KSIAZKI
WHERE ID NOT IN
  (SELECT DISTINCT E.IDKSIAZKI
  FROM B_WYPOZYCZENIA W
  JOIN B_EGZEMPLARZE E
  ON E.ID = W.IDEGZEMPLARZE
  );
  
  
SELECT * FROM B_CZYTELNICY WHERE LTRIM (UPPER(NAZWISKO)) LIKE 'M%';


SELECT K.TYTUL
FROM B_WYPOZYCZENIA W
JOIN B_EGZEMPLARZE E
ON E.ID=W.IDEGZEMPLARZE
JOIN B_KSIAZKI K
ON K.ID           =E.IDKSIAZKI
WHERE IDCZYTELNICY=338;


SELECT K.TYTUL,
  K.AUTOR
  /*  4 */
FROM B_WYPOZYCZENIA W
JOIN B_EGZEMPLARZE E
ON E.ID=W.IDEGZEMPLARZE
JOIN B_KSIAZKI K
ON K.ID                    =E.IDKSIAZKI
WHERE W.DATA_WYPOZYCZENIA >= TO_DATE('2012/05/16', 'yyyy/mm/dd')
AND W.DATA_WYPOZYCZENIA   <= TO_DATE ('2015/09/14', 'yyyy/mm/dd');


SELECT K.TYTUL,
  K.AUTOR
FROM B_WYPOZYCZENIA W
JOIN B_EGZEMPLARZE E
ON E.ID=W.IDEGZEMPLARZE
JOIN B_KSIAZKI K
ON K.ID=E.IDKSIAZKI
WHERE W.DATA_WYPOZYCZENIA BETWEEN TO_DATE('16052001','DDMMYYYY') AND TO_DATE('16092015','DDMMYYYY');
/*  5 */
/*  6 */
SELECT DISTINCT TO_CHAR(W.DATA_WYPOZYCZENIA,'DAY')
FROM B_WYPOZYCZENIA W
JOIN B_EGZEMPLARZE E
ON E.ID = W.IDEGZEMPLARZE
WHERE IDKSIAZKI = 44
AND DATA_WYPOZYCZENIA BETWEEN TO_DATE('2014/12/01', 'yyyy/mm/dd') AND TO_DATE('2016/12/20', 'yyyy/mm/dd');

/* 7 */

SELECT C.IMIE, C.NAZWISKO
FROM B_CZYTELNICY C JOIN B_WYPOZYCZENIA W ON C.ID=w.idczytelnicy 
JOIN B_EGZEMPLARZE E ON W.IDEGZEMPLARZE=E.ID
WHERE E.IDKSIAZKI=112 AND DATA_WYPOZYCZENIA 
BETWEEN TO_DATE ('20111201', 'yyyymmdd') 
AND TO_DATE ('20171231','yyyymmdd'); 

/*  8  */
SELECT IMIE, NAZWISKO, ADRES_MIASTO
FROM B_CZYTELNICY
WHERE ADRES_KOD LIKE '66%'; 

/*  9  */
SELECT ID, IMIE, NAZWISKO
FROM B_BIBLIOTEKARZE
WHERE ID NOT IN
(SELECT DISTINCT IDBIBLIOTEKARZE
FROM B_WYPOZYCZENIA W 
JOIN B_EGZEMPLARZE E ON W.IDEGZEMPLARZE=E.ID 
JOIN B_KSIAZKI K ON E.IDKSIAZKI=K.ID
WHERE TYTUL<> 'Excel w obliczeniach naukowych i technicznych - licencja');  

/*  10  */
SELECT K.ID, K.AUTOR, K.TYTUL, C.ID, C.IMIE, C.NAZWISKO
FROM B_WYPOZYCZENIA W
JOIN B_CZYTELNICY C ON C.ID=W.IDCZYTELNICY
JOIN B_EGZEMPLARZE E ON E.ID = W.IDEGZEMPLARZE
JOIN B_KSIAZKI K ON K.ID=E.IDKSIAZKI
WHERE W.DATA_WYPOZYCZENIA
IN
(SELECT WW.DATA_WYPOZYCZENIA
FROM B_WYPOZYCZENIA WW
JOIN B_EGZEMPLARZE EE ON EE.ID = WW.IDEGZEMPLARZE
WHERE WW.IDCZYTELNICY =216
AND EE.IDKSIAZKI = 1013);

/*    11    */
SELECT IDCZYTELNICY
FROM B_WYPOZYCZENIA
WHERE ID NOT IN
(SELECT W.IDCZYTELNICY FROM B_WYPOZYCZENIA W 
JOIN B_EGZEMPLARZE E ON W.IDEGZEMPLARZE=E.ID 
JOIN B_KSIAZKI K ON E.IDKSIAZKI=K.ID
WHERE UPPER (K.AUTOR) LIKE '%.PIKOÑ,%' OR 
UPPER (K.AUTOR) LIKE '%.PIKOÑ' OR
UPPER (K.AUTOR) LIKE '% PIKOÑ' OR
UPPER (K.AUTOR) LIKE 'PIKOÑ_%' OR
UPPER (K.AUTOR) LIKE '%,PIKOÑ%' OR
UPPER (K.AUTOR) LIKE '% PIKOÑ,%' OR
UPPER (K.AUTOR) LIKE '% ,PIKOÑ%');


/*    12    */

SELECT IMIE, NAZWISKO, 
(SELECT MIN (DATA_WYPOZYCZENIA) FROM B_WYPOZYCZENIA WHERE IDCZYTELNICY=C.ID) PIERWSZE,
(SELECT MAX (DATA_WYPOZYCZENIA) FROM B_WYPOZYCZENIA WHERE IDCZYTELNICY=C.ID) OSTATNIE
FROM B_CZYTELNICY C ;

/*    13   */
SELECT COUNT(*), IMIE, NAZWISKO
FROM B_WYPOZYCZENIA W
JOIN B_BIBLIOTEKARZE B ON B.ID=W.IDBIBLIOTEKARZE
WHERE DATA_WYPOZYCZENIA BETWEEN TO_DATE ('2010/01/01','yyyy/mm/dd') 
AND TO_DATE ('2017/12/31','yyyy/mm/dd')
GROUP BY IMIE, NAZWISKO
ORDER BY NAZWISKO, IMIE;

/*   14   */
SELECT IDCZYTELNICY, COUNT(*)
FROM B_WYPOZYCZENIA W
JOIN B_EGZEMPLARZE E ON E.ID=W.IDEGZEMPLARZE
WHERE E.IDKSIAZKI=112
GROUP BY IDCZYTELNICY
HAVING COUNT(*)>2;

/* 15 */ 
SELECT E.IDKSIAZKI, COUNT(IDCZYTELNICY)
FROM B_EGZEMPLARZE E JOIN B_KSIAZKI K ON E.IDKSIAZKI=K.ID JOIN B_WYPOZYCZENIA W ON E.ID=w.IDEGZEMPLARZE
GROUP BY E.IDKSIAZKI
HAVING COUNT(IDCZYTELNICY)>100 ;     /* 15 */ 

/* 16 */
SELECT MAX(liczbawypozyczen) FROM(
SELECT IDCZYTELNICY, COUNT(DATA_WYPOZYCZENIA) liczbawypozyczen
FROM B_EGZEMPLARZE E JOIN B_KSIAZKI K ON E.IDKSIAZKI=k.ID JOIN B_WYPOZYCZENIA W ON E.ID=W.IDEGZEMPLARZE
GROUP BY IDCZYTELNICY);   /* 16 */

/* 17 */
SELECT MIN(liczbawypozyczen) FROM(
SELECT IDCZYTELNICY, COUNT(DATA_WYPOZYCZENIA) liczbawypozyczen
FROM B_EGZEMPLARZE E JOIN B_KSIAZKI K ON E.IDKSIAZKI=K.ID JOIN B_WYPOZYCZENIA W ON E.ID=W.IDEGZEMPLARZE
GROUP BY IDCZYTELNICY); 

